/* Automatically @generated by tree-sitter v0.25.9 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 26
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 26
#define ALIAS_COUNT 1
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 5

enum ts_symbol_identifiers {
  anon_sym_EQ = 1,
  anon_sym_COLON = 2,
  anon_sym_LBRACK = 3,
  anon_sym_RBRACK = 4,
  anon_sym_PLUS = 5,
  anon_sym_DASH = 6,
  anon_sym_LPAREN = 7,
  anon_sym_RPAREN = 8,
  sym_number = 9,
  sym_float = 10,
  sym_string = 11,
  sym_identifier = 12,
  sym_source = 13,
  sym__expr = 14,
  sym__literal = 15,
  sym__numeric = 16,
  sym__stringy = 17,
  sym__scalar = 18,
  sym_assignment = 19,
  sym_pair = 20,
  sym_index = 21,
  sym_binary = 22,
  sym_negation = 23,
  sym_paren = 24,
  aux_sym_source_repeat1 = 25,
  alias_sym_key = 26,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_EQ] = "=",
  [anon_sym_COLON] = ":",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "minus",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_number] = "number",
  [sym_float] = "float",
  [sym_string] = "string",
  [sym_identifier] = "identifier",
  [sym_source] = "source",
  [sym__expr] = "_expr",
  [sym__literal] = "_literal",
  [sym__numeric] = "_numeric",
  [sym__stringy] = "_stringy",
  [sym__scalar] = "_scalar",
  [sym_assignment] = "assignment",
  [sym_pair] = "pair",
  [sym_index] = "index",
  [sym_binary] = "binary",
  [sym_negation] = "negation",
  [sym_paren] = "paren",
  [aux_sym_source_repeat1] = "source_repeat1",
  [alias_sym_key] = "key",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_number] = sym_number,
  [sym_float] = sym_float,
  [sym_string] = sym_string,
  [sym_identifier] = sym_identifier,
  [sym_source] = sym_source,
  [sym__expr] = sym__expr,
  [sym__literal] = sym__literal,
  [sym__numeric] = sym__numeric,
  [sym__stringy] = sym__stringy,
  [sym__scalar] = sym__scalar,
  [sym_assignment] = sym_assignment,
  [sym_pair] = sym_pair,
  [sym_index] = sym_index,
  [sym_binary] = sym_binary,
  [sym_negation] = sym_negation,
  [sym_paren] = sym_paren,
  [aux_sym_source_repeat1] = aux_sym_source_repeat1,
  [alias_sym_key] = alias_sym_key,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym__numeric] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym__stringy] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym__scalar] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_index] = {
    .visible = true,
    .named = true,
  },
  [sym_binary] = {
    .visible = true,
    .named = true,
  },
  [sym_negation] = {
    .visible = true,
    .named = true,
  },
  [sym_paren] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_key] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_key,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
};

static const TSSymbol ts_supertype_symbols[SUPERTYPE_COUNT] = {
  sym__expr,
  sym__literal,
  sym__numeric,
  sym__scalar,
  sym__stringy,
};

static const TSMapSlice ts_supertype_map_slices[] = {
  [sym__expr] = {.index = 0, .length = 4},
  [sym__literal] = {.index = 4, .length = 2},
  [sym__numeric] = {.index = 6, .length = 2},
  [sym__scalar] = {.index = 8, .length = 2},
  [sym__stringy] = {.index = 10, .length = 2},
};

static const TSSymbol ts_supertype_map_entries[] = {
  [0] =
    sym__literal,
    sym_binary,
    sym_negation,
    sym_paren,
  [4] =
    sym__numeric,
    sym_string,
  [6] =
    sym_float,
    sym_number,
  [8] =
    sym__numeric,
    sym_identifier,
  [10] =
    sym_identifier,
    sym_string,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      ADVANCE_MAP(
        '"', 1,
        '(', 10,
        ')', 11,
        '+', 8,
        '-', 9,
        ':', 5,
        '=', 4,
        '[', 6,
        ']', 7,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(14);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_identifier);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source] = STATE(23),
    [sym__expr] = STATE(13),
    [sym__literal] = STATE(9),
    [sym__numeric] = STATE(8),
    [sym_assignment] = STATE(2),
    [sym_pair] = STATE(2),
    [sym_index] = STATE(2),
    [sym_binary] = STATE(9),
    [sym_negation] = STATE(9),
    [sym_paren] = STATE(9),
    [aux_sym_source_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACK] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [sym_number] = ACTIONS(11),
    [sym_float] = ACTIONS(13),
    [sym_string] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
  },
  [STATE(2)] = {
    [sym__expr] = STATE(13),
    [sym__literal] = STATE(9),
    [sym__numeric] = STATE(8),
    [sym_assignment] = STATE(3),
    [sym_pair] = STATE(3),
    [sym_index] = STATE(3),
    [sym_binary] = STATE(9),
    [sym_negation] = STATE(9),
    [sym_paren] = STATE(9),
    [aux_sym_source_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_LBRACK] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [sym_number] = ACTIONS(11),
    [sym_float] = ACTIONS(13),
    [sym_string] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
  },
  [STATE(3)] = {
    [sym__expr] = STATE(13),
    [sym__literal] = STATE(9),
    [sym__numeric] = STATE(8),
    [sym_assignment] = STATE(3),
    [sym_pair] = STATE(3),
    [sym_index] = STATE(3),
    [sym_binary] = STATE(9),
    [sym_negation] = STATE(9),
    [sym_paren] = STATE(9),
    [aux_sym_source_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_DASH] = ACTIONS(26),
    [anon_sym_LPAREN] = ACTIONS(29),
    [sym_number] = ACTIONS(32),
    [sym_float] = ACTIONS(35),
    [sym_string] = ACTIONS(38),
    [sym_identifier] = ACTIONS(41),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(46), 1,
      sym_number,
    ACTIONS(44), 10,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_string,
      sym_identifier,
  [16] = 8,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      sym_number,
    ACTIONS(13), 1,
      sym_float,
    ACTIONS(15), 1,
      sym_string,
    STATE(8), 1,
      sym__numeric,
    STATE(22), 1,
      sym__expr,
    STATE(9), 4,
      sym__literal,
      sym_binary,
      sym_negation,
      sym_paren,
  [44] = 8,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      sym_number,
    ACTIONS(13), 1,
      sym_float,
    ACTIONS(15), 1,
      sym_string,
    STATE(8), 1,
      sym__numeric,
    STATE(11), 1,
      sym__expr,
    STATE(9), 4,
      sym__literal,
      sym_binary,
      sym_negation,
      sym_paren,
  [72] = 8,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      sym_number,
    ACTIONS(13), 1,
      sym_float,
    ACTIONS(15), 1,
      sym_string,
    STATE(8), 1,
      sym__numeric,
    STATE(10), 1,
      sym__expr,
    STATE(9), 4,
      sym__literal,
      sym_binary,
      sym_negation,
      sym_paren,
  [100] = 2,
    ACTIONS(50), 1,
      sym_number,
    ACTIONS(48), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_string,
      sym_identifier,
  [115] = 2,
    ACTIONS(54), 1,
      sym_number,
    ACTIONS(52), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_string,
      sym_identifier,
  [130] = 2,
    ACTIONS(58), 1,
      sym_number,
    ACTIONS(56), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_string,
      sym_identifier,
  [145] = 2,
    ACTIONS(62), 1,
      sym_number,
    ACTIONS(60), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_string,
      sym_identifier,
  [160] = 2,
    ACTIONS(66), 1,
      sym_number,
    ACTIONS(64), 9,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_float,
      sym_string,
      sym_identifier,
  [175] = 3,
    ACTIONS(70), 1,
      anon_sym_PLUS,
    ACTIONS(72), 1,
      sym_number,
    ACTIONS(68), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_LPAREN,
      sym_float,
      sym_string,
      sym_identifier,
  [191] = 2,
    ACTIONS(76), 1,
      sym_number,
    ACTIONS(74), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_LPAREN,
      sym_float,
      sym_string,
      sym_identifier,
  [204] = 2,
    ACTIONS(80), 1,
      sym_number,
    ACTIONS(78), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_LPAREN,
      sym_float,
      sym_string,
      sym_identifier,
  [217] = 2,
    ACTIONS(84), 1,
      sym_number,
    ACTIONS(82), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_LPAREN,
      sym_float,
      sym_string,
      sym_identifier,
  [230] = 2,
    ACTIONS(88), 1,
      sym_number,
    ACTIONS(86), 7,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_DASH,
      anon_sym_LPAREN,
      sym_float,
      sym_string,
      sym_identifier,
  [243] = 5,
    ACTIONS(11), 1,
      sym_number,
    ACTIONS(13), 1,
      sym_float,
    ACTIONS(90), 1,
      sym_identifier,
    STATE(24), 1,
      sym__numeric,
    STATE(25), 1,
      sym__scalar,
  [259] = 5,
    ACTIONS(11), 1,
      sym_number,
    ACTIONS(13), 1,
      sym_float,
    ACTIONS(15), 1,
      sym_string,
    STATE(8), 1,
      sym__numeric,
    STATE(16), 1,
      sym__literal,
  [275] = 2,
    STATE(17), 1,
      sym__stringy,
    ACTIONS(92), 2,
      sym_string,
      sym_identifier,
  [283] = 2,
    ACTIONS(94), 1,
      anon_sym_EQ,
    ACTIONS(96), 1,
      anon_sym_COLON,
  [290] = 2,
    ACTIONS(70), 1,
      anon_sym_PLUS,
    ACTIONS(98), 1,
      anon_sym_RPAREN,
  [297] = 1,
    ACTIONS(100), 1,
      ts_builtin_sym_end,
  [301] = 1,
    ACTIONS(102), 1,
      anon_sym_RBRACK,
  [305] = 1,
    ACTIONS(104), 1,
      anon_sym_RBRACK,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 16,
  [SMALL_STATE(6)] = 44,
  [SMALL_STATE(7)] = 72,
  [SMALL_STATE(8)] = 100,
  [SMALL_STATE(9)] = 115,
  [SMALL_STATE(10)] = 130,
  [SMALL_STATE(11)] = 145,
  [SMALL_STATE(12)] = 160,
  [SMALL_STATE(13)] = 175,
  [SMALL_STATE(14)] = 191,
  [SMALL_STATE(15)] = 204,
  [SMALL_STATE(16)] = 217,
  [SMALL_STATE(17)] = 230,
  [SMALL_STATE(18)] = 243,
  [SMALL_STATE(19)] = 259,
  [SMALL_STATE(20)] = 275,
  [SMALL_STATE(21)] = 283,
  [SMALL_STATE(22)] = 290,
  [SMALL_STATE(23)] = 297,
  [SMALL_STATE(24)] = 301,
  [SMALL_STATE(25)] = 305,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__numeric, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__numeric, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__literal, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__literal, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expr, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary, 3, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary, 3, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_negation, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_negation, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren, 3, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paren, 3, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__stringy, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__stringy, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_index, 3, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_index, 3, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 3, 0, 1),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pair, 3, 0, 1),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [100] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__scalar, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ctstest(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .supertype_map_slices = ts_supertype_map_slices,
    .supertype_map_entries = ts_supertype_map_entries,
    .supertype_symbols = ts_supertype_symbols,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "ctstest",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
